---
title: "c13-project"
author: "Isabel de Luis"
date: "2025-04-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
if (!require(dplyr)) install.packages("arrow")
if (!require(readr)) install.packages("readr")

library(tidyverse)
library(arrow)
library(ggplot2)
library(tidyr)
library(dplyr)
library(readr)

```

## Data

```{r}
df_feb_25_green <- read_parquet("data/project/green_tripdata_2025-02.parquet")
df_feb_25_yellow <- read_parquet("data/project/yellow_tripdata_2025-02.parquet")

df_feb_24_green <- read_parquet("data/project/green_tripdata_2024-02.parquet")
df_feb_24_yellow <- read_parquet("data/project/yellow_tripdata_2024-02.parquet")
```

```{r}

df_feb_25_green <- 
  df_feb_25_green |>
  mutate(year = 2025,
         color = "green")

df_feb_24_green <- 
  df_feb_24_green |>
  mutate(year = 2024,
         color = "green")

df_feb_25_yellow <- 
  df_feb_25_yellow |>
  mutate(year = 2025,
         color = "yellow")

df_feb_24_yellow <- 
  df_feb_24_yellow |>
  mutate(year = 2024,
         color = "yellow")
df_combined <- bind_rows(df_feb_25_green, df_feb_25_yellow, df_feb_24_green, df_feb_24_yellow)
```

## Plots
```{r}
df_combined |>
  filter(payment_type < 3 & total_amount >= 0 & year == 2025) |>
  ggplot(aes(x = color, y = cbd_congestion_fee)) +
  geom_point()
```


```{r}
df_combined |>
  filter(payment_type < 3 & total_amount >= 0) |>
  ggplot(aes(x = color, y = total_amount)) +
  geom_boxplot() +
  facet_wrap("year")
```
```{r}

```


